name: moneturn-book-club
services:
  database:
    image: postgres:16.6-alpine3.21
    volumes:
      - database:/var/lib/postgresql/data
    env_file: packages/database/.env
    ports:
      - "5432:5432"
  backend:
    depends_on:
      - database
    env_file: packages/backend/.env
    build: ./packages/backend
    ports:
      - "8080:8080"
    links:
      - database
  frontend:
    depends_on:
      - backend
    env_file: packages/frontend/.env
    build: ./packages/frontend
    ports:
      - "3000:3000"
    links:
      - backend
volumes:
  database:
